### ISSUE TITLE
which version of Guice should I use?

### ISSUE THREAD

**Issue by morgwai** [GuicedEE/Services#16]
Hello,
I've created a small [lib that provides websocket guice scopes](https://github.com/morgwai/servlet-scopes) for `javax` websockets and now I'm looking into providing `jakarta` support and while searching for `jakarta` version of Guice, I stumbled on GuicedEE project. I'm however very confused by the versioning:
- I couldn't find any information which version of GuicedEE corresponds to which version of upstream Guice (or of other libs to that matter)
- https://guicedee.com/ says the latest version is `1.1.0.0` but it seems a bit outdated: build date (2020/11/13) is before the latest release of upstream Guice (5.0.1 was released in February 2021)
- maven search says the latest version is `62`, but I _guess_ it's a mistake release given incoherence of numbering
- the latest stable "4-number" version in maven central is `1.2.0.2`, but only a build with classifier `jre16` exists, while I'm targeting java 11
- `1.2.0.1` has a build for java 11, but it seems to be broken: I get `Failed to read artifact descriptor for com.guicedee.services:guice:jar:1.2.0.1-jre11: Could not find artifact com.guicedee:versioner:pom:1.2.0.1-jre11 in central (https://repo.maven.apache.org/maven2)` error
- versions `1.1.1.8`..`1.2.0.0` have only builds for java 15 and 16

In the end I found that the latest version that seems to be working with java 11 is `1.1.1.7`: in my experimental build of jakarta support I use the [build without any classifier](https://github.com/morgwai/servlet-scopes/blob/v4.0-jakarta-experimental/pom.xml#L196) and it seems ok, but I'm really not sure by now if this is the 1 I should be using nor even which version of Guice it corresponds to... Please kindly advise.
Thanks!

**Comment by GedMarc** [comment]
It is currently on Guice 7 (y), and all imports should come directly
